---
  - hosts: osp-director
    tasks:

    - name: Register System with Subscription_Manager
      command: "{{ item }}"
      with_items:
        - /usr/sbin/subscription-manager register --autosubscribe --username=rhn-gps-rbuilta --password=gusszz07 --force

    - name: Disable repos
      command: "{{ item }}"
      with_items:
        - /usr/sbin/subscription-manager repos --disable=*

    - name: Add repos
      command: /usr/sbin/subscription-manager repos --enable="{{ item }}"
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-rh-common-rpms
        - rhel-7-server-satellite-tools-6.1-rpms
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-8-director-rpms
        - rhel-7-server-openstack-8-rpms
        - rhel-7-server-rhceph-1.3-osd-rpms
        - rhel-7-server-rhceph-1.3-mon-rpms

    - name: Updating the OS
      command: /usr/bin/dnf -y update
